### ISSUE TITLE
Consider ditching serde, expose AsBytes trait

### ISSUE THREAD

**Issue by blt** [postmates/hopper#6]
Nom has this neat trait called [AsBytes](https://docs.rs/nom/2.0.1/nom/trait.AsBytes.html) and I wonder if a similar idiom might not be useful for hopper. At present we require that every `T` which comes into hopper implement Serialize and Deserialize from serde. This works pretty well. But! In some projects I _know_ I can make a faster serializer than what serde can offer just because I'm aware of the very specific problem domain. 

No dice. I still have to use serde. 

If hopper exposed an AsBytes that use-case could be made workable.

**Comment by skade** [comment]
I'm currently pondering if a facade lib that abstracts over serde and other serializers/deserializers would be helpful.

**Comment by blt** [comment]
@skade Oh dear, sorry, I missed your comment. 

I could get behind that. Or, I guess, since serde appears to be the defacto standard perhaps this issue is really about implemented a custom serde serializer / deserializer.

**Comment by skade** [comment]
The problem is that this also introduces a very hard and very slow to build dependency into the whole thing. Using serde::* as a generic interface might be an issue because many libraries implement very _specific_ versions of serde, which might make passing types from those into this lib hard. A smaller, more generic, interface can express a far wider version expectation and still work.

**Comment by blt** [comment]
That is true. I am still a fan of nom's AsBytes. Do you have your notion written up anywhere?
